package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.PowerShellStep
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildConfigurationName'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildConfigurationName")) {
    expectSteps {
        powerShell {
            name = "first step"
            id = "first_step"
            scriptMode = file {
                path = "firstStep.ps1"
            }
            param("jetbrains_powershell_script_code", """Write-Host "hello world"""")
        }
    }
    steps {
        update<PowerShellStep>(0) {
            clearConditions()
            scriptMode = file {
                path = "firstStep2FromTC.ps1"
            }
        }
    }
}
